---
- name: Exercise for deploying my server to an EC2
  hosts: all
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root

  vars:
    - ansible_host_key_checking: false

  roles:
    - apache
