---
- name: Update apt packages
  become: yes
  apt:
    update_cache: yes

- name: Upgrade packages
  become: yes
  apt:
    upgrade: yes

- name: Install apache web server
  apt:
    name: apache2
    state: latest

- name: Delete default HTML page
  become: yes
  file:
    path: /var/www/html/index.html
    state: absent
